inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'bench.rb'
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'test/**/*'
Style/NumericLiterals:
  MinDigits: 6
