language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - jruby
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
matrix:
  allow_failures:
    - rvm: rbx
branches:
  only:
    - master
env: JRUBY_OPTS='--1.9'
